services:
  # PostgreSQL Database
  - type: postgres
    name: lol-analytics-db
    plan: free
    ipAllowList: []

  # Backend Spring Boot service
  - type: web
    name: lol-analytics-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: RIOT_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: lol-analytics-db
          property: connectionString
      - key: DATABASE_USERNAME
        fromDatabase:
          name: lol-analytics-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: lol-analytics-db
          property: password

  # Frontend React service
  - type: web
    name: lol-analytics-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://lol-analytics-backend.onrender.com 